source "https://rubygems.org"
ruby "3.4.8"

gem "activerecord", "~> 7.2"
gem "dotenv", "~> 2.8"
gem "roda", "~> 3.90"
gem "sqlite3", "~> 1.7"
gem "tilt", "~> 2.4"
gem "zai-ruby-sdk", path: "/home/worajedt/RubymineProjects/z-ai-sdk-ruby"

group :development, :test do
  gem "database_cleaner-active_record", "~> 2.1"
  gem "rack-test", "~> 2.1"
  gem "rake", "~> 13.2"
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.65"
  gem "rubocop-capybara", "~> 2.21"
  gem "rubocop-rake", "~> 0.6"
  gem "rubocop-rspec", "~> 3.0"
  gem "rubocop-thread_safety", "~> 0.5"
end

group :development do
  gem "rackup", "~> 2.1"
  gem "rerun", "~> 0.14"
  gem "webrick", "~> 1.8"
end

gem "erb", "~> 6.0"
